<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>News - Notícia</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?=BASE_URL?>css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?=BASE_URL?>css/1-col-portfolio.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	<span id="new-id"><?=$newId?></span>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#" id="link-home"><big>News Site</big></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="javascript: return false;" id="link-admin">Admin</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container" id="page-content">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Notícias
                    <small>nacionais e internacionais</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Notícias -->
        <div class="row"  id="list-new">
        	<!-- Conteúdo inserido via JQuery -->
        </div>
        <!-- /.row -->


        <!-- Footer -->
        <footer>
        	<hr>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Fernando Henriques <?=$year?></p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?=BASE_URL?>js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="<?=BASE_URL?>js/bootstrap.min.js"></script>
    <!-- Custom JSs -->
    <script src="<?=BASE_URL?>js/for.all.js"></script>
    <script src="<?=BASE_URL?>js/new.js"></script>

</body>

</html>
