<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>News - Login</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="<?=BASE_URL?>css/bootstrap.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="<?=BASE_URL?>css/styles.css" rel="stylesheet">
	</head>
	<body>
		<!--login modal-->
		<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog">
		
		   		<div class="modal-content">
		      		<div class="modal-header">
		         		 <h1 class="text-center">Login</h1>
		      		</div>
		      		<div class="modal-body">
			        	<form class="form col-md-12 center-block" id="form-login">
			        		
				          	<div class="form-group" id="error"></div>
				            <div class="form-group">
				              <input type="email" id="email" name="email" class="form-control input-lg" placeholder="E-mail" required>
				            </div>
				            <div class="form-group">
				              <input type="password" id="password" name="password" class="form-control input-lg" placeholder="Senha" required>
				            </div>
				            <div class="form-group">
				              <button class="btn btn-primary btn-lg btn-block my-btn">Entrar</button>
				              <!--<span class="pull-right"><a href="#">Register</a></span><span><a href="#">Need help?</a></span>-->
				            </div>
			            
			        	</form>
		     		</div>
		     		<div class="modal-footer"></div>
		  		</div>
		  	
	   		</div> 
	    </div>
	    <!-- Jquery -->
	    <script src="<?=BASE_URL?>js/jquery.js"></script>
	    <!-- Bootstrap -->
	    <script src="<?=BASE_URL?>js/bootstrap.min.js"></script>
	    <!-- Custom JSs -->
	    <script src="<?=BASE_URL?>js/for.all.js"></script>
	    <script src="<?=BASE_URL?>js/login.js"></script>

	</body>
</html>